CREATE CONSTRAINT skill_name IF NOT EXISTS
FOR (s:Skill)
REQUIRE s.name IS UNIQUE;

CREATE CONSTRAINT job_title IF NOT EXISTS
FOR (j:Job)
REQUIRE j.title IS UNIQUE;

CREATE CONSTRAINT company_name IF NOT EXISTS
FOR (c:Company)
REQUIRE c.name IS UNIQUE;